app/hello_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf.urls import include
from .views import user_list_view, index, solo_view, login_view, register_view, local_view, ranking_view, ranked_view, tournament_view, profile_view
from channels.routing import ProtocolTypeRouter, URLRouter
from channels.auth import AuthMiddlewareStack


urlpatterns = [
    path('', index, name='index'),
    path('solo/', solo_view, name='solo'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('local/', local_view, name='local'),
    path('ranking/', ranking_view, name='ranking'),
    path('ranked/', ranked_view, name='ranked'),
    path('tournament/', tournament_view, name='tournament'),
    path('profile/', profile_view, name='profile'),
    path('qrcode/', views.afficher_qr_code, name='qrcode'),
	path('edit/', views.edit_profile, name='edit'),
	# Friend
	path('add_friend/<int:friend_id>/', views.add_friend, name='add_friend'),
	path('add_friend_username/<str:username>/', views.add_friend_username, name='add_friend_username'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
	path('accept_friend/<int:request_id>/', views.accept_friend_request, name='accept_friend'),
    path('reject_friend/<int:request_id>/', views.reject_friend_request, name='reject_friend'),
    path('api/get_friends/', views.get_friends, name='get_friends'),
	path('api/remove_friend/', views.remove_friend, name='remove_friend'),
	path('api/get_friend_requests/', views.get_friend_requests, name='get_friend_requests'),
	# API 42
	path('connexion_42/', views.connexion_42, name='connexion_42'),
	path('redirection_apres_authentification/', views.redirection_apres_authentification, name='redirection_apres_authentification'),
    path('exchange_code_for_access_token/<str:code>/', views.exchange_code_for_access_token, name='exchange_code_for_access_token'),
	# API
	path('api/get_user/', views.api_user_view.as_view(), name='get_user'),
    path('api/users/', views.api_user_list.as_view(), name='user-list'),
	path('api/users/<int:id>/', views.api_user_details.as_view(), name='user-details'),
	path('api/match/', views.api_match_list.as_view(), name='match-list'),
	path('api/match/<int:id>/', views.api_match_details.as_view(), name='match-details'),
	path('api/tournaments/', views.api_tournois_list.as_view(), name='match-list'),
	path('api/tournaments/<int:id>/', views.api_tournois_details.as_view(), name='match-details'),
    # ADMIN
    path('adminer/', lambda request: redirect('http://:8080/'), name='adminer_redirect'),
    # DEV
    path('users/', user_list_view, name='user_list'),
	path('exemple', views.exemple_view, name='exemple'),
	path('edit_profile', views.edit_profile, name='edit_profile'),
	## path('connected-users/', views.get_connected_users, name='get_connected_users'),
    # WEBSOCKETS
	path('check-match/', views.check_match, name='check_match'),
	path('api/join-match/', views.JoinMatch.as_view(), name='join_match'),
    path('api/create-match/', views.CreateMatch.as_view(), name='create_match'),
    path('api/create-tournament/', views.JoinTournament.as_view(), name='create_tournament'),
	path('api/get_user/', views.CurrentUser.as_view(), name='curent_user'),
	path('api/create-final-match/<int:tournament_id>/', views.CreateFinalMatch.as_view(), name='create_final_match'),
]

app/hello_django/models.py
from django.db import models
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from pathlib import Path
import os
from django.core.files import File
import urllib.request
from PIL import Image
from django.db import transaction

# TODO LIST :
    # historique tournoi: position, date, résultat dernier match, adversaire dernier match
    # historique ranked: résultat (victoire ou défaite), score, adversaire, gain de lp

def validate_password_length(value):
    if len(value) < 8:
        raise ValidationError("Le mot de passe doit contenir au moins 8 caractères.")

class user_list(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    username = models.CharField(max_length=12, validators=[ASCIIUsernameValidator()])
    password = models.CharField(max_length=128, validators=[validate_password_length])
    email = models.CharField(max_length=50)
    profile_picture = models.ImageField(upload_to='photos/', default='photos/default-profile.jpg')
    status = models.CharField(max_length=20, default='offline', choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('in_game', 'En jeu')])
    last_login = models.DateTimeField(null=True, blank=True)
    double_auth = models.BooleanField(default=1)
    is_log = models.BooleanField(default=0)
    intra = models.BooleanField(default=False)
    qr_code = models.ImageField(upload_to='qr_codes/')
    jwt_token = models.CharField(max_length=500, blank=True, null=True)
    # Parties:
    games_played = models.PositiveIntegerField(default=0)
    games_win = models.PositiveIntegerField(default=0)
    games_loose = models.PositiveIntegerField(default=0)
    games_rank = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    # Friend:
    friends = models.ManyToManyField('self', symmetrical=False, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def is_authenticated(self):
        return True

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'django_user_list'

# Friend

class Friendship(models.Model):
    from_user = models.ForeignKey(user_list, related_name='friend_requests_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(user_list, related_name='friend_requests_received', on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

@receiver(post_save, sender=user_list)
def sync_user_to_auth_user(sender, instance, created, **kwargs):
    if created:
        User.objects.create_user(
            username=instance.username,
            password=instance.password,
            email=instance.email,
            first_name=instance.first_name,
            last_name=instance.last_name
        )

class Match(models.Model):
    player1 = models.ForeignKey('user_list', related_name='player1_matches', on_delete=models.CASCADE)
    player2 = models.ForeignKey('user_list', related_name='player2_matches', on_delete=models.CASCADE, null=True)
    score_player1 = models.IntegerField(default=0)
    score_player2 = models.IntegerField(default=0)
    player_winner = models.ForeignKey('user_list', related_name='winner_matches', on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, default='waiting', choices=[('waiting', 'En attente de joueurs'), ('end_game', 'Fin de partie'), ('in_game', 'En jeu'), ('cancel', 'Annulé')])
    locked = models.BooleanField(default=False)

    def update_scores(self):
        if not self.locked:
            with transaction.atomic():
                self.locked = True
                self.player1.games_played += 1
                self.player2.games_played += 1
                if self.score_player1 > self.score_player2:
                    self.player1.games_win += 1
                    self.player2.games_loose += 1
                    self.player1.games_rank += 25
                    if self.player2.games_rank >= 25:
                        self.player2.games_rank -= 25
                elif self.score_player1 < self.score_player2:
                    self.player2.games_win += 1
                    self.player1.games_loose += 1
                    self.player2.games_rank += 25
                    if self.player1.games_rank >= 25:
                        self.player1.games_rank -= 25
                self.player1.save()
                self.player2.save()
                self.save()

class Tournament(models.Model):
    date_tournament = models.DateTimeField(auto_now_add=True)
    player01 = models.ForeignKey('user_list', related_name='player01_tournaments', on_delete=models.CASCADE)
    player02 = models.ForeignKey('user_list', related_name='player02_tournaments', on_delete=models.CASCADE, null=True)
    player03 = models.ForeignKey('user_list', related_name='player03_tournaments', on_delete=models.CASCADE, null=True)
    player04 = models.ForeignKey('user_list', related_name='player04_tournaments', on_delete=models.CASCADE, null=True)
    player_winner = models.ForeignKey('user_list', related_name='winner_matches_tournaments', on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, default='waiting', choices=[('waiting', 'En attente de joueurs'), ('end_game', 'Fin de tournoi'), ('in_game', 'En jeu'), ('cancel', 'Annulé')])
    match1_id = models.IntegerField(null=True)
    match2_id = models.IntegerField(null=True)
    final_id = models.IntegerField(null=True)

    def create_matches(self):
        match1 = Match.objects.create(player1=self.player01, player2=self.player02)
        match2 = Match.objects.create(player1=self.player03, player2=self.player04)
        self.match1_id = match1.id
        self.match2_id = match2.id
        self.save()

    def check_and_create_final(self):
        match1 = Match.objects.filter(id=self.match1_id).first()
        match2 = Match.objects.filter(id=self.match2_id).first()

        if match1 and match2 and not self.final_id:
            if match1.status in ['end_game', 'cancel'] and match2.status in ['end_game', 'cancel']:
                winner1 = match1.player_winner
                winner2 = match2.player_winner
                if winner1 and winner2:
                    final_match = Match.objects.create(player1=winner1, player2=winner2)
                    final_match.save()

                    self.final_id = final_match.id
                    self.save()

    class Meta:
        db_table = 'django_tournament'

app/hello_django/forms.py
from django import forms
from .models import user_list
from django.core.exceptions import ValidationError

class add_user_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(error_messages={'invalid': "Entrez une adresse e-mail valide."})
    username = forms.CharField(error_messages={'invalid': "Entrez un nom d'utilisateur valide."})

    class Meta:
        model = user_list
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'profile_picture']

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        if user_list.objects.filter(username=username).exists():
            raise ValidationError("Ce nom d'utilisateur existe déjà.")

        if user_list.objects.filter(email=email).exists():
            raise ValidationError("Cet e-mail existe déjà.")

        return cleaned_data

class loginForm(forms.Form):
    username = forms.CharField(label='Nom d\'utilisateur', required=False, widget=forms.TextInput(attrs={'placeholder': 'Pseudonyme', 'id': 'usernameInput'}))
    password = forms.CharField(label='Mot de passe', required=False, widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe', 'id': 'passwordInput'}))
    token = forms.CharField(label='Clé d\'authentification', required=False, widget=forms.TextInput(attrs={'placeholder': 'Clé d\'authentification', 'id': 'tokenInput'}))

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = user_list
        fields = ['first_name', 'last_name', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['profile_picture'].required = False

app/templates/edit_profile.html
{% extends 'index.html' %}

{% block content %}
<div class="text-white mx-auto text-center rounded-3 border border-light my-auto p-2 d-flex flex-column justify-content-center" style="background: linear-gradient(to right, #0D6EFD, #F4ACBC); width: 35%; height: 60%; border-width: 3px !important;">
	<h2>Editer le profil</h2>
	<form id="editForm" method="post">
		{% csrf_token %}
		<div class="log-input d-flex flex-column align-items-center">
			{{ form.first_name }}
			<div id="firstMissing" class="text-danger d-none">Veuillez saisir un prénom</div>
		</div>
		<div>
			<div class="log-input d-flex flex-column align-items-center my-2">
				{{ form.last_name }}
				<div id="lastMissing" class="text-danger d-none">Veuillez saisir un nom</div>
			</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center my-2">
			<input type="file" id="id_profile_picture" name="profile_picture" accept=".jpg,.jpeg,.png">
		</div>
		<div>
			<button class="btn btn-light" type="submit">Sauvegarder</button>
		</div>
	</form>
</div>
{% endblock %}

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Transcendence</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="icon" href="{% static 'images/icon.ico' %}" type="image/x-icon">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Anta&display=swap" rel="stylesheet">

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body class="bg-dark" style="font-family: 'Anta', sans serif;">

	<header class="text-white d-flex justify-content-between header-size border-bottom border-primary" style="border-width: 4px !important;">
		<a class="redir text-white my-auto ml-4" href="/">
			<h1 class="h4">🏳️‍⚧️endence</h1>
		</a>
		<div id="auth-data" class="d-none" data-authenticated="{{ user.is_authenticated }}"></div>
		<div id="profilebar" class="my-auto mr-4">
			<a id="linkProfile" href="{% url 'profile' %}?id={{ user.id }}" class="redir">
				<img id="userAvatar" src="{{ user.profile_picture.url }}" class="profile-bar border border-primary" style="border-width: 2px !important;">
			</a>
		</div>
		<div id="logbutton" class="flex my-auto mr-4">
			<div class="mr-2">
				<button class="btn btn-outline-light redir px-2 py-1" href="{% url 'login' %}">Se connecter</button>
			</div>
			<div>
				<button class="btn btn-outline-light redir px-2 py-1" href="{% url 'register' %}">S'inscrire</button>
			</div>
		</div>
	</header>
	<div id="notification" class="notification" style="display: none;"></div>
	<div class="d-flex">
		<aside id="friendbar" class="main-height text-white border-right border-primary rounded-5 d-flex flex-column justify-content-between" style="width: 15%; border-width: 3px !important;">
			<div id="friend-list" class="pl-4 pr-2 pt-3">
				<h4>Ami(e)s</h4>
				<div id="friends-user" class="friend-user"></div>
			</div>
			<div id="friend-request" class="pl-4 pr-2 pt-3">
				<h4>Demandes</h4>
				<div id="friends-scroll" class="friend-scroll"></div>
			</div>
			<div id="add-friend" class="input-wrapper pl-3 pr-3 mb-3">
				<input type="text" placeholder="Ajouter un ami..." id="add-friend-input" class="input">
			</div>
			<div id="logrequire" class="main-height flex flex-column align-items-center justify-content-center mx-auto">
				<img src="{% static 'images/not_connected.svg' %}" class="img-fluid mb-3" style="width: 50vh; height: 15vh;">
				<p class="text-center text-white m-0" >Veuillez vous connecter</p>
			</div>
		</aside>

		<main id="content" class="main-height d-flex w-100">
			{% block content %}
			<div class="mx-auto text-white text-center my-auto d-flex flex-column">
				<h2>Bienvenue sur notre Transcendence !</h2>
				<img src="{% static 'images/welcome.gif' %}">
			</div>
			{% endblock %}
		</main>
	</div>

		<footer class="bottom-size border-top border-primary my-auto d-flex justify-content-center" style="border-width: 4px !important;">
		<nav class="navbar navbar-expand navbar-nav justify-content-between mx-5 w-100">
			<a class="nav-item nav-link text-white redir" href="/solo/">🤖Solo</a>
			<a class="nav-item nav-link text-white redir" href="/local/">🕹️Local</a>
			<a class="nav-item nav-link text-white redir" href="/ranked/">⚔️Ranked</a>
			<a class="nav-item nav-link text-white redir" href="/tournament/">🏆Tournoi</a>
			<a class="nav-item nav-link text-white redir" href="/ranking/">👑Classement</a>
		</nav>
	</footer>
	<script src="{% static 'js/router.js' %}"></script>
	<script src="{% static 'js/local.js' %}"></script>
	<script src="{% static 'js/solo.js' %}"></script>
	<script src="{% static 'js/ranked.js' %}"></script>
	<script src="{% static 'js/login.js' %}"></script>
	<script src="{% static 'js/register.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="{% static 'js/friend.js' %}"></script>
	<script src="{% static 'js/online.js' %}"></script>
<<<<<<< HEAD
	<script src="{% static 'js/tournament.js' %}"></script>
	<script src="{% static 'js/edit.js' %}"></script>
=======
	<script src="{% static 'js/edit.js' %}"></script>
	<script src="{% static 'js/tournament.js' %}"></script>
>>>>>>> tom
</body>
</html>

app/templates/local.html
{% extends 'index.html' %}

{% block content %}
<div class="d-flex flex-column justify-content-center mx-auto">
	<h2 class="text-white text-center mx-auto my-0">LOCAL</h2>
	<canvas id="canvas2" class="my-2" width="640" height="480"></canvas>
	<div class="d-flex justify-content-center">
		<button id="start-local" class="btn btn-primary">Start</button>
	</div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'index.html' %}

{% block content %}
<div id="logcontent" class="text-white mx-auto text-center rounded-3 border border-light my-auto p-2 d-flex flex-column justify-content-center" style="background: linear-gradient(to right, #0D6EFD, #F4ACBC); width: 35%; height: 65%; border-width: 3px !important;">
	<h2>Se connecter</h2>
	<form id="loginForm" method="post">
		{% csrf_token %}
		<div class="log-input d-flex flex-column align-items-center">
			{{ form.username }}
			<div id="usernameMissing" class="text-danger d-none">Veuillez saisir votre identifiant</div>
		</div>
		<div>
			<div class="log-input d-flex flex-column align-items-center my-2">
				{{ form.password }}
				<div id="passwordMissing" class="text-danger d-none">Veuillez saisir votre mot de passe</div>
			</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center my-2">
			{{ form.token }}
			<div id="tokenMissing" class="text-danger d-none">Veuillez saisir votre clé d'authentification</div>
		</div>
		<div>
			<button class="btn btn-light" type="submit">Se connecter</button>
		</div>
	</form>
	<form class="mt-2" action="{% url 'connexion_42' %}" method="get">
		{% csrf_token %}
		<button type="submit" style="color:#ffffff" class="btn btn-dark">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24" font-size-adjust="14px"><path d="M24 12.42l-4.428 4.415H24zm-4.428-4.417l-4.414 4.418v4.414h4.414V12.42L24 8.003V3.575h-4.428zm-4.414 0l4.414-4.428h-4.414zM0 15.996h8.842v4.43h4.412V12.42H4.428l8.826-8.846H8.842L0 12.421z"></path></svg>
			<span class="ml-1">Intra</span>
		</button>
	</form>
</div>
{% endblock %}

app/templates/qr_code.html
{% extends 'index.html' %}

{% block content %}
<div class="d-flex flex-column text-white justify-content-center mx-auto">
	<h1 class="text-center">QR Code de {{ user.username }}</h1>
	<p class="text-center">Conservez cette clé, elle vous servira lors de votre prochaine connexion, car l'A2F est obligatoire sur notre Transcendence. Si vous perdez votre clé, veuillez contacter le support.</p>
	<img class="mx-auto" src="{{ user.qr_code.url }}" style="width: 350; height: 350px;">
</div>
{% endblock %}

app/templates/ranked.html
{% extends 'index.html' %}

{% block content %}
<div class="d-flex flex-column justify-content-center mx-auto">
	<h2 class="text-white text-center mx-auto my-0">RANKED</h2>
	<div class="d-flex justify-content-center">
		<p id="adversaire-match" style="display: none; color:white;">Adversaire déconnecté</p>
	</div>
	<canvas id="canvas3" class="my-2" width="640" height="480"></canvas>
	<div class="d-flex justify-content-center">
		<button id="start-ranked" class="btn btn-primary">Trouver un adversaire</button>
		<p id="searching-match" class="d-none" style="color:white;">Recherche de match en cours...</p>
	</div>
</div>
{% endblock %}

app/templates/ranking.html
{% extends 'index.html' %}

{% block content %}
<div id="ranking" class="d-flex flex-column justify-content-center text-white text-center mx-auto">
    <h2 class="mx-auto my-0 pb-3">CLASSEMENT</h2>
    <div class="overflow-auto rounded-3 mb-4 ranking-scrollbar" style="max-height: 65vh;">
        <table class="table table-striped table-dark m-0" style="width: 80vh;">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Rank</th>
                    <th scope="col">Victoires</th>
                    <th scope="col">Défaites</th>
                </tr>
            </thead>
            <tbody>
                {% for player in top_players %}
                <tr>
                    <th scope="row">{{ player.position }}</th>
                    <td>
                        <a class="redir text-white" href="/profile/?id={{ player.id }}">{{ player.username }}</a>
                    </td>
                    <td>{{ player.games_rank }}</td>
                    <td>{{ player.games_win }}</td>
                    <td>{{ player.games_loose }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'index.html' %}

{% block content %}
<div id="logcontent" class="text-white mx-auto text-center rounded-3 border border-light my-auto p-2 d-flex flex-column justify-content-center" style="background: linear-gradient(to right, #0D6EFD, #F4ACBC); width: 35%; height: 75%; border-width: 3px !important;">
	<h2>S'inscrire</h2>
	<form id="registerForm" method="post" class="mb-1">
		{% csrf_token %}
		<div class="log-input d-flex flex-column align-items-center">
			<input id="id_first_name" required maxlength="15" name="first_name" placeholder="Prénom" type="text"/>
			<div id="firstMissing" class="text-danger d-none">Veuillez saisir votre prénom</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center my-2">
			<input id="id_last_name" required maxlength="15" name="last_name" placeholder="Nom" type="text"/>
			<div id="lastMissing" class="text-danger d-none">Veuillez saisir votre nom</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center">
			<input id="id_username" required maxlength="15" name="username" placeholder="Identifiant" type="text"/>
			<div id="usernameMissingReg" class="text-danger d-none">Veuillez saisir votre identifiant</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center my-2">
			<input id="id_password" required name="password" placeholder="Mot de passe" type="password"/>
			<div id="passwordMissingReg" class="text-danger d-none">Veuillez saisir votre mot de passe</div>
		</div>
		<div class="log-input d-flex flex-column align-items-center">
			<input id="id_email" required name="email" maxlength="320" placeholder="Email" type="email"/>
			<div id="emailMissing" class="text-danger d-none">Veuillez saisir votre email</div>
		</div>
		<div>
			<button class="btn btn-light mt-2" type="submit">S'inscrire</button>
		</div>
	</form>
</div>
{% endblock %}

app/templates/solo.html
{% extends 'index.html' %}

{% block content %}
<div class="d-flex flex-column justify-content-center mx-auto">
	<h2 class="text-white text-center mx-auto my-0">SOLO</h2>
	<canvas id="canvas1" class="my-2" width="640" height="480"></canvas>
	<div class="d-flex justify-content-center">
		<button id="start-solo" class="btn btn-primary">Start</button>
	</div>
</div>
{% endblock %}

app/templates/user_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des Utilisateurs</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- CSS personnalisé -->
    <link rel="stylesheet" href="{% static 'css/userlist.css' %}">
</head>
<body>
<div class="container">
    <h1>Liste des Utilisateurs</h1>
    <div class="card-deck">
        {% for user in users %}
        <div class="card">
            <!-- Image de profil (si disponible) -->
            <img src="{{ user.profile_picture.url }}" class="card-img-top" alt="Photo de Profil">
            <div class="card-body">
                <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                <p class="card-text">{{ user.username }}</p>
				<p class="card-text">{{ user.status }}</p>
                <p class="card-text">URL {{ user.profile_picture.url }}</p>
                <p class="card-text">Mail: {{ user.email }}</p>
                <p class="card-text">Parties Jouées: {{ user.games_played }}</p>
                <p class="card-text">Victoire: {{ user.games_win }}</p>
                <p class="card-text">Défaite: {{ user.games_loose }}</p>
                <p class="card-text">Rang: {{ user.games_rank }}</p>
				<p class="card-text">dernière connexion: {{ user.last_login }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

</body>
</html>